---
# tasks file for roles/common
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2

- name: Add Kubernetes signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes
    state: present
  notify:
    - Restart kubelet

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Disable Swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^\s*[^#].*swap\s'
    line: '# commented out by Ansible'

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl params for Kubernetes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
    - { key: 'net.ipv4.ip_forward', value: 1 }
