---
- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_init

- name: Create .kube directory
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644

- name: Install Flannel network plugin
  ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


# Save the join command to be used by worker nodes
- name: Save kubeadm join command
  copy:
    content: "{{ kubeadm_init.stdout_lines[4] }}"
    dest: /join-command
