---
# tasks file for roles/master
- name: Initialize the Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

# - name: Ensure .kube directory exists in user's home
#   file:
#     path: "/home/{{ ansible_user }}/.kube"
#     state: directory
#     mode: '0755'

- name: Ensure .kube directory exists in user's home
  file:
    path: "/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to user's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Download Helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: "/tmp/get-helm-3"
    mode: '0755'

- name: Add Helm repository GPG key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Helm repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install Helm
  apt:
    name: helm
    state: present
    update_cache: yes

- name: Add Cilium Helm repository
  command: helm repo add cilium https://helm.cilium.io/

- name: Update Helm repository
  command: helm repo update

- name: Install Cilium
  command: helm install cilium cilium/cilium --version 1.14.4 --namespace kube-system
  environment:
     KUBECONFIG: /{{ ansible_user }}/.kube/config


# - name: Install Cilium
#   command: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml
